import type { Metadata } from "next";
import "./globals.css";
import { Providers } from '../src/providers'



export const metadata: Metadata = {
  title: "Gestion de cabañas",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

